# Generated by Django 4.2 on 2026-02-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_options_alter_job_skills_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.TextField(),
        ),
    ]
