# Generated by Django 4.2 on 2026-03-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
