# Generated by Django 4.2 on 2026-03-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='matched_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='missing_skills',
            field=models.TextField(blank=True),
        ),
    ]
