# Generated by Django 4.2 on 2026-03-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_application_matched_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_percentage',
            field=models.FloatField(default=0),
        ),
    ]
