# Generated by Django 4.2 on 2026-03-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_latitude_job_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='interview_type',
            field=models.CharField(choices=[('online', 'Online Interview'), ('offline', 'Offline Interview')], default='offline', max_length=10),
        ),
    ]
