# Generated by Django 6.0.3 on 2026-03-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_application_interview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.TextField(help_text='Comma separated skills'),
        ),
    ]
