# Generated by Django 6.0.3 on 2026-03-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_application_interview_type_alter_job_skills_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_score',
            field=models.FloatField(default=0),
        ),
    ]
