# Generated by Django 6.0.3 on 2026-03-17

from django.db import migrations, models


def populate_job_categories(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')

    category_rules = [
        (
            'it',
            [
                'software', 'developer', 'development', 'engineer', 'backend', 'front end',
                'frontend', 'full stack', 'fullstack', 'web', 'devops', 'qa', 'testing',
                'cloud', 'python', 'java', 'django', 'react', 'node', 'api'
            ]
        ),
        (
            'data-science',
            [
                'data science', 'data scientist', 'data analyst', 'analytics', 'analysis',
                'machine learning', 'ml', 'artificial intelligence', 'ai', 'deep learning',
                'nlp', 'computer vision', 'pytorch', 'tensorflow', 'llm'
            ]
        ),
        (
            'marketing',
            [
                'marketing', 'digital marketing', 'seo', 'sem', 'content', 'social media',
                'brand', 'growth', 'campaign', 'copywriter', 'copywriting'
            ]
        ),
        (
            'finance',
            [
                'finance', 'financial', 'accountant', 'accounting', 'auditor', 'banking',
                'investment', 'tax', 'payroll', 'bookkeeping', 'budget'
            ]
        ),
        (
            'design',
            [
                'design', 'designer', 'ui', 'ux', 'product design', 'graphic', 'visual',
                'figma', 'illustrator', 'photoshop', 'wireframe', 'prototype'
            ]
        ),
        (
            'mobile-app-development',
            [
                'mobile', 'android', 'ios', 'flutter', 'react native', 'swift', 'kotlin',
                'xamarin', 'ionic', 'app developer'
            ]
        ),
    ]

    for job in Job.objects.all():
        searchable_text = " ".join(
            filter(
                None,
                [
                    getattr(job, 'title', ''),
                    getattr(job, 'skills_required', ''),
                    getattr(job, 'description', ''),
                ]
            )
        ).lower()

        best_category = 'it'
        best_score = -1

        for category_slug, keywords in category_rules:
            score = sum(1 for keyword in keywords if keyword in searchable_text)

            if score > best_score:
                best_score = score
                best_category = category_slug

        job.category = best_category
        job.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_application_interview_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(
                choices=[
                    ('it', 'IT / Software Jobs'),
                    ('data-science', 'Data Science / AI Jobs'),
                    ('marketing', 'Marketing Jobs'),
                    ('finance', 'Finance Jobs'),
                    ('design', 'Design Jobs'),
                    ('mobile-app-development', 'Mobile App Development'),
                ],
                default='it',
                max_length=40,
            ),
        ),
        migrations.RunPython(populate_job_categories, migrations.RunPython.noop),
    ]
