# Generated by Django 6.0.3 on 2026-03-17

from django.db import migrations, models


def convert_offline_interviews_to_online(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    Application = apps.get_model('jobs', 'Application')

    Job.objects.filter(interview_type='offline').update(interview_type='online')
    Application.objects.filter(interview_type='Offline').update(interview_type='Online')


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_job_category'),
    ]

    operations = [
        migrations.RunPython(
            convert_offline_interviews_to_online,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='application',
            name='interview_type',
            field=models.CharField(
                choices=[('Online', 'Online')],
                default='Online',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='job',
            name='interview_type',
            field=models.CharField(
                choices=[('online', 'Online Interview')],
                default='online',
                max_length=10,
            ),
        ),
    ]
