# Generated by Django 6.0.3 on 2026-03-17

from django.db import migrations


def seed_remaining_category_jobs(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')

    sample_jobs = [
        {
            "title": "Digital Marketing Specialist",
            "company": "GrowthSpark Media",
            "location": "Mumbai",
            "category": "marketing",
            "job_type": "Full Time",
            "salary": "6 LPA",
            "interview_type": "online",
            "description": "Plan digital campaigns, optimize SEO strategy, and manage social media performance for brand growth.",
            "skills_required": "SEO, Google Ads, Social Media Marketing, Analytics, Content Strategy",
            "experience_required": "2-4 Years",
        },
        {
            "title": "Content Marketing Executive",
            "company": "BrightReach Studio",
            "location": "Pune",
            "category": "marketing",
            "job_type": "Full Time",
            "salary": "5 LPA",
            "interview_type": "online",
            "description": "Create and manage content calendars, campaign messaging, and conversion-focused copy across digital channels.",
            "skills_required": "Content Writing, Copywriting, Email Marketing, Campaign Planning, SEO",
            "experience_required": "1-3 Years",
        },
        {
            "title": "Financial Analyst",
            "company": "Axis Wealth Partners",
            "location": "Bengaluru",
            "category": "finance",
            "job_type": "Full Time",
            "salary": "7 LPA",
            "interview_type": "online",
            "description": "Analyze business performance, forecast budgets, and create financial reports for leadership teams.",
            "skills_required": "Financial Modeling, Excel, Budgeting, Forecasting, Reporting",
            "experience_required": "2-4 Years",
        },
        {
            "title": "Accounts Executive",
            "company": "LedgerOne Solutions",
            "location": "Hyderabad",
            "category": "finance",
            "job_type": "Full Time",
            "salary": "4.8 LPA",
            "interview_type": "online",
            "description": "Handle reconciliations, invoice processing, GST documentation, and daily accounting operations.",
            "skills_required": "Accounting, Tally, GST, Reconciliation, Bookkeeping",
            "experience_required": "1-3 Years",
        },
        {
            "title": "UI/UX Designer",
            "company": "PixelCraft Labs",
            "location": "Chennai",
            "category": "design",
            "job_type": "Full Time",
            "salary": "7.5 LPA",
            "interview_type": "online",
            "description": "Design intuitive product journeys, wireframes, and high-fidelity interfaces for modern web applications.",
            "skills_required": "Figma, Wireframing, Prototyping, UX Research, UI Design",
            "experience_required": "2-4 Years",
        },
        {
            "title": "Graphic Designer",
            "company": "CreativeMint Agency",
            "location": "Delhi",
            "category": "design",
            "job_type": "Full Time",
            "salary": "5.5 LPA",
            "interview_type": "online",
            "description": "Create marketing creatives, visual assets, and brand design systems across digital and social campaigns.",
            "skills_required": "Photoshop, Illustrator, Branding, Visual Design, Social Media Creatives",
            "experience_required": "1-3 Years",
        },
        {
            "title": "Flutter Developer",
            "company": "AppNest Technologies",
            "location": "Noida",
            "category": "mobile-app-development",
            "job_type": "Full Time",
            "salary": "8 LPA",
            "interview_type": "online",
            "description": "Build high-performance mobile applications for Android and iOS using Flutter and modern architecture patterns.",
            "skills_required": "Flutter, Dart, REST API, Firebase, Mobile UI",
            "experience_required": "2-4 Years",
        },
        {
            "title": "Android Developer",
            "company": "Mobiloft Systems",
            "location": "Gurugram",
            "category": "mobile-app-development",
            "job_type": "Full Time",
            "salary": "7 LPA",
            "interview_type": "online",
            "description": "Develop and maintain Android apps with scalable architecture, API integration, and performance optimization.",
            "skills_required": "Android, Kotlin, Java, REST API, Jetpack",
            "experience_required": "2-4 Years",
        },
    ]

    for job_data in sample_jobs:
        Job.objects.get_or_create(
            title=job_data["title"],
            company=job_data["company"],
            category=job_data["category"],
            defaults=job_data,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_remove_offline_interview'),
    ]

    operations = [
        migrations.RunPython(seed_remaining_category_jobs, migrations.RunPython.noop),
    ]
