# Generated by Django 6.0.3 on 2026-03-31 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_application_data(apps, schema_editor):
    Application = apps.get_model("jobs", "Application")
    ApplicationTimeline = apps.get_model("jobs", "ApplicationTimeline")

    status_map = {
        "Pending": "Applied",
        "Reviewed": "Under Review",
        "Shortlisted": "Under Review",
        "Rejected": "Rejected",
    }

    seen_pairs = set()
    for application in Application.objects.select_related("user", "job").order_by("id"):
        pair = (application.user_id, application.job_id)
        if pair in seen_pairs:
            application.delete()
            continue
        seen_pairs.add(pair)

        user = application.user
        full_name = f"{user.first_name} {user.last_name}".strip() or user.username
        application.full_name = application.full_name or full_name
        application.email = application.email or getattr(user, "email", "") or ""
        application.phone_number = application.phone_number or ""
        application.status = status_map.get(application.status, application.status)
        if not application.overall_score:
            application.overall_score = application.match_percentage or application.match_score or 0
        if not application.final_score:
            application.final_score = application.overall_score
        application.save()

        if not ApplicationTimeline.objects.filter(application=application).exists():
            ApplicationTimeline.objects.create(
                application=application,
                status=application.status,
                note="Migrated into the upgraded hiring workflow.",
            )


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_savedjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='application',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='communication_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='confidence_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='final_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='generated_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='hr_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='overall_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='salary_suggestion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='submitted_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='technical_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Interview Completed', 'Interview Completed'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationtimeline',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_timeline_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationtimeline',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='jobs.application'),
        ),
        migrations.RunPython(backfill_application_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_application_per_user_and_job'),
        ),
    ]
